version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: comments_api_dev
    env_file:
      - .env
    command: pnpm run dev
    volumes:
      - .:/app                 
      - /app/node_modules
    ports:
      - "${API_PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - comments_net

  db:
    image: postgres:13.22-trixie
    container_name: comments_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - comments_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:

networks:
  comments_net:
    driver: bridge
