FROM node:22-alpine
WORKDIR /app
RUN corepack enable && corepack use pnpm@10.15.0
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
# el código (src/) se montará como volumen en runtime
EXPOSE 3000
CMD ["pnpm", "run", "dev"]
